on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

name: render-documentation

jobs:
  render-documentation:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: n1hility/cancel-previous-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-pandoc@v1
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-r-dependencies@v1
      - uses: r-lib/actions/setup-tinytex@v1

      - name: Cache across documentation builds
        uses: action/cache@v2
        with:
          path: **/.cache

      - name: Render project summary
        run: |
          rmarkdown::render("docs/summary/index.Rmd", output_dir = "docs")
        shell: Rscript {0}

      - name: Render evaluation report
        run: |
          rmarkdown::render("docs/real-time/index.Rmd")
        shell: Rscript {0}

      - name: Render method evaluation report
        run: |
          rmarkdown::render("docs/real-time-method-comparison/index.Rmd")
        shell: Rscript {0}
 
      - name: Render paper
        run: |
          rmarkdown::render("writeup/paper.Rmd", output_dir = "docs")
        shell: Rscript {0}

      - name: Render SI
        run: |
          rmarkdown::render("writeup/si.Rmd", output_dir = "docs")
        shell: Rscript {0}

      - name: Upload documentation
        uses: actions/upload-artifact@v2
        with:
          name: documentation
          retention-days: 5
          path: docs

  publish-documentation:
    if: github.ref == 'refs/heads/main' && github.repository == 'epiforecasts/eval-germany-sp-nowcasting'
    needs: render-documentation
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: Make a clean gh-pages branch
      run: |
        git checkout --orphan gh-pages
        git rm -rf .
    - uses: actions/download-artifact@v2
      with:
        name: documentation
        path: .
    - name: Commit and push documentation
      run: |
        git config user.email "action@github.com"
        git config user.name "GitHub Action - Published documentation"
        git add --all
        git commit -m "Published documentation"
        git push -f origin gh-pages:gh-pages
        echo "reports published to GitHub"
