on:
  schedule:
    - cron:  '6 12 * * *'
    - cron: '6 10 * * *'
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

name: render-documentation

jobs:
  render-documentation:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
      - uses: r-lib/actions/setup-tinytex@v2

      - name: Cache across documentation builds
        uses: actions/cache@v2
        with:
          path: '**/.cache'
          key: caches

      - name: Render project summary
        run: |
          rmarkdown::render("docs/summary/index.Rmd", output_dir = "docs")
        shell: Rscript {0}

      - name: Render evaluation report
        run: |
          rmarkdown::render("docs/real-time/index.Rmd")
        shell: Rscript {0}

      - name: Render method evaluation report
        run: |
          rmarkdown::render("docs/real-time-method-comparison/index.Rmd")
        shell: Rscript {0}

      - name: Render paper
        run: |
          rmarkdown::render("writeup/paper.Rmd", output_dir = "docs")
        shell: Rscript {0}

      - name: Render SI
        run: |
          rmarkdown::render("writeup/si.Rmd", output_dir = "docs")
        shell: Rscript {0}

      - name: Deploy to GitHub pages 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: docs
          single-commit: true
          clean: true
